
const S='ielts100_online';let st=JSON.parse(localStorage.getItem(S)||'{}');st.done=st.done||{};st.notes=st.notes||{};st.err=st.err||[];st.saved=st.saved||{};const save=()=>localStorage.setItem(S,JSON.stringify(st));
const topics=['Education','Technology','Environment','Work','Health','Society','Travel','Culture','Crime','Language'];
const grammar=['Present Simple vs Present Continuous','Past Simple vs Past Continuous','Present Perfect','Articles','Subject–Verb Agreement','Comparatives & Superlatives','Modal Verbs','Passive Voice','Relative Clauses','Conditionals','Gerunds & Infinitives','Linking Ideas','Prepositions for Task 1','Word Formation','Complex Sentences'];
const start=new Date('2026-09-21T00:00:00');
function cd(){let n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(start.getFullYear(),start.getMonth(),start.getDate());return Math.max(1,Math.min(100,Math.floor((a-b)/86400000)+1))}
function dateOf(d){let x=new Date(start);x.setDate(x.getDate()+d-1);return x.toLocaleDateString('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'})}
function phase(d){return d<=70?'Học giáo trình':d<=84?'Học lại phần sai':d<=96?'Mock + correction':'Giảm tải trước thi'}
function slots(d){let u=Math.min(10,Math.ceil(Math.min(d,70)/7)),g=grammar[(d-1)%grammar.length],t=topics[u-1];if(d<=70)return[['05:00–05:50','grammar','Grammar • '+g],['05:50–06:45','reading','Reading • '+t],['06:45–07:30','listening','Listening • '+t],['07:30–08:00','vocab','Vocabulary • '+t],['16:15–17:30','writing','Writing • '+t],['17:30–18:15','speaking','Speaking • '+t],['18:15–18:45','review','Review 1–3–7'],['18:45–19:20','fix','Fix mistakes'],['19:20–20:00','mixed','Weak-skill drill']];return[['05:00–06:00','review','Review / Mock'],['06:00–07:00','reading','Reading repair'],['07:00–08:00','listening','Listening repair'],['16:15–17:30','writing','Writing repair'],['17:30–18:15','speaking','Speaking repair'],['18:15–19:00','fix','Error Log'],['19:00–20:00','mixed','Integrated review']]}
function key(d,i){return d+'_'+i}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById('view-'+v).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v))}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));
function renderDays(){let e=document.getElementById('dayGrid'),c=cd();e.innerHTML='';for(let d=1;d<=100;d++){let b=document.createElement('button');b.textContent=d;if(d===c)b.classList.add('current');if(slots(d).every((_,i)=>st.done[key(d,i)]))b.classList.add('done');b.onclick=()=>{renderToday(d);show('today')};e.appendChild(b)}}
function renderToday(d=cd()){let s=slots(d),h='<div class="dayHeader"><div><span class="phase">'+phase(d)+'</span><h2>Day '+d+' • '+dateOf(d)+'</h2><div class="muted">Unit '+Math.min(10,Math.ceil(Math.min(d,70)/7))+'</div></div></div><h3>Bấm vào từng khung để học ngay</h3><div class="slots">';s.forEach((x,i)=>h+='<button class="slot '+(st.done[key(d,i)]?'done':'')+'" data-i="'+i+'"><span class="time">'+x[0]+'</span><span><b>'+x[2]+'</b><small>Learn → Practice → Check → Fix → Review</small></span></button>');h+='</div><h3>Ghi chú Day '+d+'</h3><textarea id="note" class="note">'+(st.notes[d]||'')+'</textarea>';document.getElementById('todayCard').innerHTML=h;document.querySelectorAll('.slot').forEach(b=>b.onclick=()=>openLesson(d,+b.dataset.i));document.getElementById('note').oninput=e=>{st.notes[d]=e.target.value;save()}}
function renderRoadmap(){let h='';for(let d=1;d<=100;d++)h+='<div class="roadDay"><b>Day '+d+' • '+dateOf(d)+'</b><div class="muted">'+phase(d)+'</div><button class="btn primary" onclick="renderToday('+d+');show(\\'today\\')">Mở Day '+d+'</button></div>';document.getElementById('roadmapList').innerHTML=h}
function renderGrammar(){document.getElementById('grammarList').innerHTML=grammar.map(x=>'<div class="grammarCard"><h3>'+x+'</h3><p>Học rule → examples → 20 câu → 3 câu tự viết → sửa lỗi.</p></div>').join('')}
function renderSaved(){let a=Object.values(st.saved);document.getElementById('savedWords').innerHTML=a.length?a.map(x=>'<div class="reviewItem"><b>'+x.w+'</b> — '+x.m+'</div>').join(''):'<p class="muted">Chưa lưu từ nào.</p>'}
function progress(){let t=0,d=0;for(let i=1;i<=100;i++)slots(i).forEach((_,j)=>{t++;if(st.done[key(i,j)])d++});let p=Math.round(d/t*100);document.getElementById('pct').textContent=p;document.getElementById('bar').style.width=p+'%';document.getElementById('progressText').textContent=d+'/'+t+' nhiệm vụ hoàn thành'}

function lessonText(type,d){if(type==='grammar')return '<div class="learnBox"><h3>Learn • 8 phút</h3><p><b>'+grammar[(d-1)%grammar.length]+'</b></p><p>Đọc rule, nhìn ví dụ, tìm signal words và tự nói lại quy tắc bằng lời của bạn.</p></div>'+quizHTML(20)+'<div class="writeBox"><h3>3 câu tự viết • 10 phút</h3><textarea class="prod"></textarea><textarea class="prod"></textarea><textarea class="prod"></textarea></div>';
if(type==='reading')return '<div class="learnBox"><h3>Reading • 55 phút</h3><p><b>Passage:</b> Online learning has expanded access to education for people who cannot easily attend a physical classroom. Its flexibility is a major advantage, but it also requires self-management. Without a fixed timetable, some learners postpone tasks until deadlines are close. Regular feedback and opportunities to interact with other learners can improve engagement.</p><p>Strategy: skim → locate evidence → identify paraphrase → answer.</p></div>'+quizHTML(12);
if(type==='listening')return '<div class="learnBox"><h3>Listening • 45 phút</h3><button id="playAudio" class="btn primary">▶ Play</button><p id="script" style="display:none">The library will close at five o clock this Friday. Students can use Room 204 until nine p.m. Laptop loans finish at four thirty.</p><button id="showScript" class="btn">Transcript</button></div>'+quizHTML(10);
if(type==='writing')return '<div class="learnBox"><h3>Writing • 75 phút</h3><p>Prompt: Some people think schools should focus mainly on academic subjects, while others believe practical life skills are equally important. Discuss both views and give your own opinion.</p><p>Analyse → outline → timed write → self-check → rewrite.</p></div><textarea class="prod" style="min-height:360px"></textarea>';
if(type==='speaking')return '<div class="learnBox"><h3>Speaking • 45 phút</h3><p>Part 1: What do you usually do after school?</p><p>Part 2: Describe a skill you would like to improve.</p><p>Part 3: How has technology changed learning?</p><textarea class="prod" placeholder="Ghi 5 lỗi sau khi tự nghe lại..."></textarea></div>';
if(type==='vocab')return '<div class="learnBox"><h3>Vocabulary • 30 phút</h3><p>academic performance • practical skills • equal access • digital literacy • sustainable development • work-life balance • career prospects • public health • quality of life • social support • learning outcome • public transport</p><p>Double-click bất kỳ từ nào để tra nghĩa online.</p></div>';
return '<div class="learnBox"><h3>Review / Fix</h3><p>Wrong → Why → Rule → Correct. Làm lại lỗi trước khi nhìn đáp án.</p><textarea class="prod" style="min-height:250px"></textarea></div>'}
function quizHTML(n){let h='<div class="quizBox"><h3>Practice • '+n+' câu</h3>';for(let i=1;i<=n;i++)h+='<div class="q"><b>'+i+'. Choose the best answer.</b><button class="opt">Option A</button><button class="opt">Option B</button><button class="btn">💡 Gợi ý</button></div>';return h+'</div>'}
function openLesson(d,i){let s=slots(d)[i];document.getElementById('lessonOverlay').classList.add('open');document.body.style.overflow='hidden';document.getElementById('lessonTitle').innerHTML='<div class="phase">DAY '+d+' • '+s[1].toUpperCase()+'</div><h2>'+s[2]+'</h2>';document.getElementById('lessonBody').innerHTML=lessonText(s[1],d)+'<div class="lessonActions"><button id="finish" class="btn green">Đã hoàn thành block</button></div>';if(document.getElementById('playAudio'))document.getElementById('playAudio').onclick=()=>{let u=new SpeechSynthesisUtterance(document.getElementById('script').textContent);u.lang='en-GB';speechSynthesis.speak(u)};if(document.getElementById('showScript'))document.getElementById('showScript').onclick=()=>{let x=document.getElementById('script');x.style.display=x.style.display==='none'?'block':'none'};document.getElementById('finish').onclick=()=>{st.done[key(d,i)]=true;save();progress();renderDays();document.getElementById('finish').textContent='✓ Đã hoàn thành'}}
document.getElementById('lessonClose').onclick=()=>{document.getElementById('lessonOverlay').classList.remove('open');document.body.style.overflow='';renderToday();};

const dict=document.getElementById('dictionary');document.getElementById('dictButton').onclick=()=>dict.classList.add('open');document.getElementById('dictClose').onclick=()=>dict.classList.remove('open');document.getElementById('dictMin').onclick=()=>dict.classList.toggle('min');document.getElementById('dictMax').onclick=()=>dict.classList.toggle('max');
let dg=false,dx=0,dy=0,hd=document.getElementById('dictHandle');hd.onpointerdown=e=>{if(e.target.closest('button'))return;let r=dict.getBoundingClientRect();dg=true;dx=e.clientX-r.left;dy=e.clientY-r.top};hd.onpointermove=e=>{if(!dg)return;dict.style.left=Math.max(0,e.clientX-dx)+'px';dict.style.top=Math.max(0,e.clientY-dy)+'px';dict.style.right='auto';dict.style.bottom='auto'};hd.onpointerup=()=>dg=false;
const clean=w=>(w||'').trim().toLowerCase().replace(/^[^a-z]+|[^a-z'-]+$/g,'');
async function tr(t){try{let r=await fetch('https://api.mymemory.translated.net/get?q='+encodeURIComponent(t)+'&langpair=en%7Cvi'),j=await r.json();return j.responseData.translatedText||''}catch(e){return''}}
async function lookup(w,s=''){w=clean(w);if(!w)return;dict.classList.add('open');document.getElementById('dictInput').value=w;let o=document.getElementById('dictResult');o.innerHTML='<div class="dictWord">'+w+'</div><p>Đang tra online…</p>';try{let r=await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/'+encodeURIComponent(w)),j=await r.json(),e=j[0],cards='';for(let m of e.meanings){let d=m.definitions[0],v=await tr(d.definition);cards+='<div class="posCard"><b>'+m.partOfSpeech+'</b><div class="definition"><div class="vi">'+v+'</div><div class="en">'+d.definition+'</div></div></div>'}let cur=e.meanings[0]?.partOfSpeech||'unknown',meaning=await tr(e.meanings[0]?.definitions[0]?.definition||w),audio=(e.phonetics||[]).find(x=>x.audio)?.audio||'';o.innerHTML='<div class="dictWord">'+w+'</div><div class="contextCard"><b>Trong câu này</b>'+(s?'<div class="contextSentence">'+s+'</div>':'')+'<div class="usage"><b>Nghĩa phù hợp</b><span>'+meaning+'</span><b>Loại từ</b><span>'+cur+'</span></div></div><h3>Tất cả loại từ / nghĩa phổ biến</h3>'+cards+'<div class="dictActions"><button id="pw">🔊 Phát âm</button><button class="save" id="sw">⭐ Lưu ôn</button></div>';document.getElementById('pw').onclick=()=>audio?new Audio(audio).play():(()=>{let u=new SpeechSynthesisUtterance(w);u.lang='en-GB';speechSynthesis.speak(u)})();document.getElementById('sw').onclick=()=>{st.saved[w]={w,m:meaning};save();renderSaved()}}catch(e){o.innerHTML='<div class="dictWord">'+w+'</div><p>Không lấy được dữ liệu lúc này.</p>'}}
function sentence(){let s=getSelection();if(!s||!s.rangeCount)return'';let n=s.getRangeAt(0).commonAncestorContainer;if(n.nodeType===3)n=n.parentElement;return(n.closest?.('p,li,.q,.example,.learnBox')||n).innerText?.slice(0,500)||''}
document.getElementById('dictGo').onclick=()=>lookup(document.getElementById('dictInput').value);document.addEventListener('dblclick',()=>{let w=getSelection().toString().trim();if(w&&/[A-Za-z]/.test(w))lookup(w,sentence())});

document.getElementById('search').oninput=e=>{let q=e.target.value.toLowerCase(),d=days.find(x=>JSON.stringify(x).toLowerCase().includes(q));if(d){renderToday(d.day);show('today')}};
renderDays();renderToday();renderRoadmap();renderGrammar();renderSaved();progress();
